### ISSUE TITLE
Setting styleBase and empty style result in exception

### ISSUE THREAD

**Issue by Khaash** [snapappointments/bootstrap-select#2239]
Initializing the selectpicker via JS and trying to set `{styleBase: 'form-control', style: ''}` as suggested in the documentation results in an exception:

> Uncaught DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
    at J.setStyle (https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.7/dist/js/bootstrap-select.min.js:8:28529)
    at J.init (https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.7/dist/js/bootstrap-select.min.js:8:14388)
    at new J (https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.7/dist/js/bootstrap-select.min.js:8:11396)
    at HTMLSelectElement.<anonymous> (https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.7/dist/js/bootstrap-select.min.js:8:12292)
    at Function.each (https://code.jquery.com/jquery-3.3.1.min.js:2:2573)
    at w.fn.init.each (https://code.jquery.com/jquery-3.3.1.min.js:2:1240)
    at w.fn.init.Q [as selectpicker] (https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.7/dist/js/bootstrap-select.min.js:8:11813)
    at HTMLDocument.init _(my_file.js)_
    at l (https://code.jquery.com/jquery-3.3.1.min.js:2:29375)
    at c (https://code.jquery.com/jquery-3.3.1.min.js:2:29677)

and the select breaks down. Changing it to `{styleBase: 'form-control', style: 'a'}`works fine so it seems the problem is only with empty strings.

Made a quick [Pluncker](https://plnkr.co/edit/KDjlNAExz6M9wPSV046W?p=preview) to show what happens

Seems it could be linked to #2221 

jQuery: 3.3.1
Bootstrap: 4.0.0
bootstrap-select: 1.13.7

**Comment by caseyjhol** [comment]
Released in [v1.13.9](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.9)!
