### ISSUE TITLE
Using a class in optgroup results in an error on refresh in chrome

### ISSUE THREAD

**Issue by riv333** [snapappointments/bootstrap-select#2442]
I tested with Version 1.13.15 with Chrome and Bootstrap 4.3.1

When one add a class in the optgroup:
```                      
<select name="test"  id="select-test" class="selectpicker w-100 test-select">
  <optgroup label="Test Options">
      <option selected>test1</option>
      <option>test2</option>
  </optgroup>
  <optgroup class="bugtest" id="bugtest-id" label="Test"> //class="bugtest" makes problems
  </optgroup>
</select>
```

And dynamically add some options with:
`$('#bugtest-id').html(options);`

Then appears an error on:
`$('#select-test').selectpicker('refresh');`

One get in Chrome the error:
```
bundle.js:1374 Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
    at Object.a (http://localhost:3000/js/bundle.js:1374:77)
    at buildElement (http://localhost:3000/js/bundle.js:2265:30)
    at Selectpicker.buildList (http://localhost:3000/js/bundle.js:2311:9)
    at Selectpicker.refresh (http://localhost:3000/js/bundle.js:3646:12)
    at HTMLSelectElement.<anonymous> (http://localhost:3000/js/bundle.js:3772:35)
    at Function.each (http://localhost:3000/js/bundle.js:9034:19)
    at jQuery.fn.init.each (http://localhost:3000/js/bundle.js:8869:17)
    at jQuery.fn.init.Plugin [as selectpicker] (http://localhost:3000/js/bundle.js:3744:22)
```

Without the class tag  `class="bugtest"` there are no problems

**Comment by caseyjhol** [comment]
Released in [v1.13.16](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.16)!
