### ISSUE TITLE
There was an issue retrieving Bootstrap's version.

### ISSUE THREAD

**Issue by ciscolive** [snapappointments/bootstrap-select#2711]
DEAR TEAM, please help solve the bug 
```ruby
bootstrap-select.js:3103 There was an issue retrieving Bootstrap's version. Ensure Bootstrap is being loaded before bootstrap-select and there is no namespace collision. If loading Bootstrap asynchronously, the version may need to be manually specified via $.fn.selectpicker.Constructor.BootstrapVersion. TypeError: Cannot read properties of undefined (reading 'Constructor')
    at jQuery2.fn.init.Plugin [as selectpicker] (bootstrap-select.js:3095:39)
    at HTMLSelectElement.<anonymous> (bootstrap-select.js:3217:14)
    at Function.each (jquery.js:385:19)
    at jQuery2.fn.init.each (jquery.js:207:17)
    at bootstrap-select.js:3215:24
    at dispatch (jquery.js:5430:27)
    at elemData.handle (jquery.js:5234:28)
```

```perl
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@hotwired/stimulus": "^3.0.1",
    "@hotwired/turbo-rails": "^7.1.1",
    "@popperjs/core": "^2.11.2",
    "bootstrap": "^5.1.3",
    "bootstrap-icons": "^1.8.1",
    "bootstrap-select": "^1.13.18",
    "esbuild": "^0.14.23",
    "jquery": "^3.6.0",
    "sass": "^1.49.8"
  },
  "scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds",
    "build:css": "sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --load-path=node_modules"
  }
}
```

**Comment by NicolasCARPi** [comment]
Hello,

Make sure bootstrap is loaded before bootstrap-select.
