### ISSUE TITLE
Arrow selection issue when live-search is false - Cannot read properties of null (reading '_selectMenuItem')

### ISSUE THREAD

**Issue by dkrvl** [snapappointments/bootstrap-select#2742]
Getting issue with arrow selection in bootstrap select with below mentions version and configuration.
- Link to issue: https://jsfiddle.net/y9oae3jv/2/
- bootstrap-select.min.js - Bootstrap-select v1.14.0-beta2
- bootstrap.bundle.min.js - Bootstrap v5.0.2

`if($('.location-select').length > 0){
$('.location-select').selectpicker({
style:"",
styleBase: 'form-control'
})
}`

_Note: if add data-live-search=**true** then not getting any kind of issue._

**&lt;select class=&quot;location-select form-select&quot; data-live-search=&quot;false&quot; placeholder=&quot;Location&quot; name=&quot;location&quot;  title=&quot;Select a number&quot; data-actions-box=&quot;false&quot; data-virtual-scroll=&quot;false&quot;&gt;
&lt;option value=&quot;AL&quot;&gt;Alabama&lt;/option&gt;
&lt;option value=&quot;WY&quot;&gt;Wyoming&lt;/option&gt;
&lt;/select&gt;**

**bootstrap.bundle.min.js:6 Uncaught TypeError: Cannot read properties of null (reading '_selectMenuItem')
at HTMLUListElement.dataApiKeydownHandler (bootstrap.bundle.min.js:6:45805)
at HTMLDocument.n (bootstrap.bundle.min.js:6:5102)
dataApiKeydownHandler @ bootstrap.bundle.min.js:6
n @ bootstrap.bundle.min.js:6**

![bsselect_issue-img2](https://user-images.githubusercontent.com/3601501/168561773-d83f509b-336b-4dd0-ba21-37129ee81b32.PNG)
![bsselect_issue-img1](https://user-images.githubusercontent.com/3601501/168561892-1251fcab-6dcc-431c-9338-2a1f1273b85c.PNG)

**Comment by dkrvl** [comment]
Is it issue in bootstrap select OR in Bootstrap 5?

**Comment by bazineta** [comment]
The problem is occurring in BS 5 due to these 3 lines:
https://github.com/snapappointments/bootstrap-select/blob/939e94b14a34759e193f616b753e0a33081cc0c5/js/bootstrap-select.js#L3587-L3589
The issue is that with 5, Bootstrap is no longer using jQuery for event management; rather, it's using a native event handler.

The plugin is attempting to turn off the normal event handling that Bootstrap's `Dropdown` is doing, then turning it back on with the `:not(.bootstrap-select) > ` preamble there to say basically, _Dear Dropdown, handle these events only if they're not for one of mine; I'll deal with those myself, thanks._

However, since BS 5 is now dealing with that using a native event handler, those three lines of jQuery event management do absolutely nothing now, so the `Dropdown` class is still handling the arrow keys, resulting in the exceptions you're seeing.

I'm not sure what an optimal solution would be, but as a quick and dirty, we just removed those 3 lines, then added the `:not(.bootstrap-select) > ` preamble to Bootstrap's own `Dropdown` event handling setup, using `patch-package` to effect the change. In the 5.2.0 ESM distribution code, it looks like this:
```
/**
 * Data API implementation
 */

EventHandler.on(document, EVENT_KEYDOWN_DATA_API, `:not(.bootstrap-select) > ${SELECTOR_DATA_TOGGLE$3}`, Dropdown.dataApiKeydownHandler);
EventHandler.on(document, EVENT_KEYDOWN_DATA_API, `:not(.bootstrap-select) > ${SELECTOR_MENU}`,          Dropdown.dataApiKeydownHandler);
EventHandler.on(document, EVENT_CLICK_DATA_API$3, Dropdown.clearMenus);
EventHandler.on(document, EVENT_KEYUP_DATA_API, Dropdown.clearMenus);
EventHandler.on(document, EVENT_CLICK_DATA_API$3, SELECTOR_DATA_TOGGLE$3, function (event) {
  event.preventDefault();
  Dropdown.getOrCreateInstance(this).toggle();
});
```
That's about as grimy a solution as there is, but for the moment, it resolves the arrow key handling.

**Comment by dkrvl** [comment]
@bazineta , Thank you for your explanation.

**Comment by vistree** [comment]
This is quite an old issue - but it seems, there is still no official fix for this problem. One question to @bazineta : 
You removed 3 lines from bootstrap-select.js - but modified only 2 in bootstrap.js. Do we need to do anything regarding the line
`.off('keydown.bs.dropdown.data-api')` ?

**Comment by vistree** [comment]
Trying your fix, I get the following error:
`event-handler.js:108 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': ':not(.bootstrap-select) > ${SELECTOR_DATA_TOGGLE$3}' is not a valid selector.
    at HTMLDocument.handler (http://example.com/themes/custom/mytheme/vendor/bootstrap-5.1.3/js/bootstrap.bundle.js?v=9.5.9:378:35)`

**Comment by bazineta** [comment]
@vistree My fix was against 5.2.0, and it appears that you're using 5.1.3 there; you'll likely need to adjust to whatever the specific requirements of 5.1.3 are.

Unfortunately, we no longer use this package, having moved on to an alternative, so that's all the insight I've got.

**Comment by vistree** [comment]
Hi @bazineta - thanx for your reply. Can you give a link to your alternative?

**Comment by bazineta** [comment]
@vistree We moved to https://tom-select.js.org/, and have been pleased with it.
